# Generated by Django 3.1.2 on 2020-10-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_text',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
