# Generated by Django 3.1.2 on 2020-10-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_auto_20201009_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_text',
            field=models.CharField(max_length=50),
        ),
    ]
