# Generated by Django 3.1.2 on 2020-10-13 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_auto_20201010_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='date_text',
        ),
        migrations.AddField(
            model_name='date',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
