# Generated by Django 3.1.2 on 2020-10-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_auto_20201013_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
